baseURL = "https://gdquest.com/"
languageCode = "en-us"
title = "GDQuest"
theme = "github.com/GDQuest/website-theme-learn"

paginate = 6
paginatePath = "page"

assetDir = "resources"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
identifier  = "tutorial"
name        = "Tuts"
url         = "/tutorial/"
weight      = 1

[[menu.main]]
identifier  = "product"
name        = "products"
url         = "/product/"
weight      = 2

[[menu.main]]
identifier  = "about"
name        = "About"
url         = "/about/"
weight      = 3

[[menu.main]]
identifier  = "news"
name        = "News"
url         = "/post/"
weight      = 3

[params.shop_link]
name        = "Shop"
url         = "https://gumroad.com/gdquest"


[permalinks]


[author]
name = "Nathan Lovato"
email = "nathan@gdquest.com"


# Site parameters
[params]
topline = "Game Design Quest"
home = "home"
highlight = "default"
stylesheet = "concise.css"

ytapikey = "AIzaSyAUCyzwHmO71chFn7wMa6VlBNzk0tpkFYk"

# Social network names for Meta tag SEO
twitter = "NathanGDQuest"

github_repo = "https://github.com/GDQuest/GDQuest-website/"
license_copyright= "GDQuest and contributors"

[params.social.1]
link = "https://www.youtube.com/c/gdquest"
icon = "youtube"
description = "GDQuest Youtube channel"

[params.social.2]
link = "https://twitter.com/NathanGDQuest"
icon = "twitter"
description = "GDQuest Twitter page"

[params.social.3]
link = "https://github.com/GDQuest/"
icon = "github"
description = "GDQuest GitHub page"

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []
