baseURL = "//gdquest.com/"
languageCode = "en-us"
title = "GDQuest"
titleCaseStyle = "Chicago"
theme = "github.com/matcornic/hugo-theme-learn"

paginate = 6
paginatePath = "page"

assetDir = "resources"

googleAnalytics = "UA-58510266-1"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.main]]
identifier  = "product"
name        = "products"
url         = "/product/"
weight      = 1

[[menu.main]]
identifier  = "news"
name        = "News"
url         = "/post/"
weight      = 2

[[menu.main]]
identifier  = "tutorial"
name        = "Tuts"
url         = "/tutorial/"
weight      = 3

[[menu.main]]
identifier  = "docs"
name        = "Docs"
url         = "/docs/"
weight      = 4

[[menu.main]]
identifier  = "about"
name        = "About"
url         = "/about/"
weight      = 5

[[menu.shortcuts]]
name = "<i class='fas fa-level-up-alt'></i>&nbsp;Back to GDQuest.com"
identifier = "gdquest.com"
url = "//"
weight = 1


[author]
name = "Nathan Lovato"
email = "nathan@gdquest.com"


# Site parameters
[params]
topline = "Game Design Quest"
home = "home"
highlight = "default"
stylesheet = "concise.css"
themeVariant = "blue"

ytapikey = "AIzaSyAUCyzwHmO71chFn7wMa6VlBNzk0tpkFYk"

# Social network names for Meta tag SEO
twitter = "NathanGDQuest"

github_repo = "//github.com/GDQuest/GDQuest-website/"
license_copyright= "GDQuest and contributors"

[params.shop_link]
name        = "Shop"
url         = "//gumroad.com/gdquest"

[[params.social]]
link = "//www.youtube.com/c/gdquest"
icon = "youtube"
description = "GDQuest Youtube channel"

[[params.social]]
link = "//twitter.com/NathanGDQuest"
icon = "twitter"
description = "GDQuest Twitter page"

[[params.social]]
link = "//github.com/GDQuest/"
icon = "github"
description = "GDQuest GitHub page"

# NOTE: from hugo 0.60.0 the default markdown formatter is Goldmark
[markup.blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

[privacy]
[privacy.googleAnalytics]
disable = false
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.youtube]
disable = false
privacyEnhanced = true

[caches]
[caches.modules]
dir = ":cacheDir/modules"
maxAge = -1