baseurl = "http://gdquest.com/"
title = "GDquest"
languageCode = "en-EN"
metaDataFormat = "yaml"

paginate = 6
paginatePath = "page"

# disqusShortname = "game-design-quest"

# Pygments code highlighting - not used
# pygmentsuseclasses = false
# pygmentsstyle = "monokai"

[[menu.main]]
identifier  = "tutorial"
name        = "Tuts"
url = "/tutorial/"
weight      = 1

# [[menu.main]]
# identifier  = "open-source"
# name        = "Apps"
# url = "/open-source/"
# weight      = 2

[[menu.main]]
identifier  = "about"
name        = "About"
url = "/about/"
weight      = 3

# [[menu.main]]
# identifier  = "post"
# name        = "Blog"
# weight      = 1

[[menu.main]]
identifier  = "shop"
name        = "Shop"
url         = "https://gumroad.com/gdquest"
weight      = 100


[permalinks]

[taxonomies]
tags = "tags"
category = "category"

[author]
name = "Nathan Lovato"
email = "nathan@gdquest.com"


# Site parameters
[params]
topline = "The Game Design Quest"
home = "home"
highlight = "default"
stylesheet = "concise.css"


# Social network names for Meta tag SEO
twitter = "NathanGDquest"
googleplus = "Gdquest"

    [params.social.1]
    link = "https://www.youtube.com/c/gdquest"
    icon = "youtube-play"
    description = "GDquest Youtube channel"
    [params.social.2]
    link = "https://www.facebook.com/gdquest"
    icon = "facebook"
    description = "GDquest Facebook page"
    [params.social.3]
    link = "https://twitter.com/NathanGDquest"
    icon = "twitter"
    description = "GDquest Twitter page"
    # [params.social.4]
    # link = "https://plus.google.com/+Gdquest"
    # icon = "google-plus-square"
    # description = "GDquest Google Plus page"

email = "nathan@gdquest.com"

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []
