baseURL = "//gdquest.com/"
languageCode = "en-us"
title = "GDQuest"
titleCaseStyle = "Chicago"
theme = "github.com/matcornic/hugo-theme-learn"

paginate = 6
paginatePath = "page"

assetDir = "resources"

googleAnalytics = "UA-58510266-1"

[outputFormats]
  [outputFormats.search]
    mediaType = "application/json"
    baseName = "search"
    isPlainText = true

[outputs]
home = [ "HTML", "RSS", "SEARCH" ]

[[menu.main]]
identifier  = "tutorial"
name        = "Tutorials"
url         = "/tutorial/"
weight      = 1

[[menu.main]]
identifier  = "tools"
name        = "Tools"
url         = "/tools/"
weight      = 2

[[menu.main]]
identifier  = "product"
name        = "products"
url         = "/product/"
weight      = 3

[[menu.main]]
identifier  = "news"
name        = "News"
url         = "/news/"
weight      = 4

[[menu.main]]
identifier  = "docs"
name        = "Docs"
url         = "/docs/"
weight      = 5

[[menu.main]]
identifier  = "about"
name        = "About"
url         = "/about/"
weight      = 6

# Shortcuts in the docs section
[[menu.shortcuts]]
name = "<i class='fas fa-level-up-alt'></i>&nbsp;Back to GDQuest.com"
identifier = "gdquest.com"
url = "//"
weight = 1


[author]
name = "Nathan Lovato"
email = "nathan@gdquest.com"


# Site parameters
[params]
topline = "Game Design Quest"
home = "home"
highlight = "default"
stylesheet = "concise.css"
themeVariant = "blue"

ytapikey = "AIzaSyAUCyzwHmO71chFn7wMa6VlBNzk0tpkFYk"

# Social network names for Meta tag SEO
twitter = "NathanGDQuest"

github_repo = "//github.com/GDQuest/GDQuest-website/"
license_copyright= "GDQuest and contributors"

[params.shop_link]
name        = "Shop"
url         = "//gdquest.mavenseed.com/courses"

[[params.social]]
link = "//www.youtube.com/c/gdquest"
icon = "youtube"
description = "GDQuest Youtube channel"

[[params.social]]
link = "//twitter.com/NathanGDQuest"
icon = "twitter"
description = "GDQuest Twitter page"

[[params.social]]
link = "//github.com/GDQuest/"
icon = "github"
description = "GDQuest GitHub page"

[[params.social]]
link = "https://discord.gg/87NNb3Z"
icon = "discord"
description = "GDQuest community on Discord"

[related]
threshold = 80.0
includeNewer = false
toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 100.0

  [[related.indices]]
  name = "date"
  weight = 10.0

[privacy]
[privacy.googleAnalytics]
disable = false
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.youtube]
disable = false
privacyEnhanced = true

[caches]
[caches.modules]
dir = ":cacheDir/modules"
maxAge = -1

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
