[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  GO_VERSION = "1.12"
  HUGO_VERSION = "0.57.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  GO_VERSION = "1.12"
  HUGO_VERSION = "0.57.2"

[context.branch-deploy]
  command = "hugo  --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  GO_VERSION = "1.12"
  HUGO_VERSION = "0.57.2"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
