[015]
TITLE= "How to use Krita for Pixel Art"
URL= "OmnpKQITm3I"

[016]
TITLE= "Painting with Krita - The Game Asset Workflow"
URL= "JCCWrLVu5VU"

[010]
TITLE= "How to paint rocks for games - part 1"
URL= "5kjHdcxpo1E"

[009]
TITLE= "How to Paint Rocks for Games - part 2"
URL= "D5djTQTMqC0"

[001]
TITLE= "How to Paint Rocks for Games - part 3"
URL= "V0GG0RVQhng"

[007]
TITLE= "Krita Animation tutorial - the animation tools in Krita 2.9 Beta"
URL= "9uvju6sUNJA"

[008]
TITLE= "Overview of the Instant Preview beta in Krita 2.9"
URL= "c9yiBRFQnbo"

[011]
TITLE= "Krita's New Features since v2.9.5"
URL= "PIKfrqk09Hk"

[012]
TITLE= "Krita Quick Tips - Convert any Brush to Pixel Art"
URL= "UM3OOwZ4NnE"

[013]
TITLE= "7 tips to master HD index painting with Krita"
URL= "1m_0DFcOPAI"

[014]
TITLE= "HD Index Painting With Krita"
URL= "PU7_FVQpTSE"

[018]
TITLE= "Painting with Krita - Getting Started"
URL= "3NlgonJuS30"

[017]
TITLE= "Painting with Krita - Getting Started part 2"
URL= "nJzn1QA_tv8"

[019]
TITLE= "Krita 2.9 review and overview of the key features"
URL= "IrmvsnDiAuc"

[020]
TITLE= "How to make your own brushes in Krita 3"
URL= "qHC3h2aTse8"

[021]
TITLE= "Krita 3 release livestream"
URL= "hlcHDRc-gN8"

[002]
TITLE= "How to Draw a Life Bar in Krita part 1"
URL= "e_LK6qadPbs"

[003]
TITLE= "How to Draw a Life Bar in Krita - part 2"
URL= "_n50mtClPBQ"

[004]
TITLE= "Krita 2.9 - Using the Tangent Normal Brush"
URL= "X0YM7a0Ri2M"

[005]
TITLE= "Krita 2.9 - Flowmap Painting Example"
URL= "193e1uzzGAk"

[006]
TITLE= "Krita 2.9 - Overview of the Tangent Normal Brush Engine"
URL= "tzS_k2z2UwU"