name = "GDquest"
license = "MIT"
description = "A hugo theme using ConciseCSS v4"
tags = ["company", "shop", "personal"]
features = ["company", "technical", "personal"]
min_version = 0.17

[author]
    name = "Nathan Lovato"
    homepage = "http://gdquest.com"
